# Generated by Django 5.2.11 on 2026-02-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sim_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='phone_line', to='telecom.simcard')),
            ],
        ),
    ]
