# Generated by Django 5.0.1 on 2026-03-02 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0003_alter_phoneline_is_deleted_alter_phoneline_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneLineHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Criada"),
                            ("STATUS_CHANGED", "Status Alterado"),
                            ("SIMCARD_CHANGED", "SIM Card Alterado"),
                            ("EMPLOYEE_CHANGED", "Usuário Alterado"),
                            ("DELETED", "Excluída"),
                            ("ALLOCATED", "Alocada"),
                            ("RELEASED", "Liberada"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="Novo Valor"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_line_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado Por",
                    ),
                ),
                (
                    "phone_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="telecom.phoneline",
                        verbose_name="Linha Telefônica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico da Linha",
                "verbose_name_plural": "Históricos das Linhas",
                "ordering": ["-changed_at"],
            },
        ),
    ]
