# Generated by Django 5.2.11 on 2026-03-03 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0004_phonelinehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonelinehistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Histórico de Linha",
                "verbose_name_plural": "Históricos de Linhas",
            },
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("STATUS_CHANGED", "Status alterado"),
                    ("SIMCARD_CHANGED", "SIM card alterado"),
                    ("EMPLOYEE_CHANGED", "Usuário alterado"),
                    ("DELETED", "Excluída"),
                    ("ALLOCATED", "Alocada"),
                    ("RELEASED", "Liberada"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="changed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alterado por",
            ),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="new_value",
            field=models.TextField(blank=True, null=True, verbose_name="Novo valor"),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="old_value",
            field=models.TextField(
                blank=True, null=True, verbose_name="Valor anterior"
            ),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="phone_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="telecom.phoneline",
                verbose_name="Linha",
            ),
        ),
        migrations.AddIndex(
            model_name="phonelinehistory",
            index=models.Index(
                fields=["phone_line", "-changed_at"],
                name="telecom_pho_phone_l_d9b6a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonelinehistory",
            index=models.Index(
                fields=["-changed_at"], name="telecom_pho_changed_0ee920_idx"
            ),
        ),
    ]
