# Generated by Django 5.2.11 on 2026-03-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0005_alter_phonelinehistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simcard",
            options={"verbose_name": "SIMcard", "verbose_name_plural": "SIMcards"},
        ),
    ]
