# Generated by Django 5.2.11 on 2026-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0006_alter_simcard_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonelinehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("STATUS_CHANGED", "Status alterado"),
                    ("SIMCARD_CHANGED", "SIM card alterado"),
                    ("EMPLOYEE_CHANGED", "Usuário alterado"),
                    ("DELETED", "Excluída"),
                    ("ALLOCATED", "Alocada"),
                    ("RELEASED", "Liberada"),
                    ("DAILY_ACTION_CHANGED", "Ação diária alterada"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
    ]
