# Generated by Django 5.2.11 on 2026-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0007_alter_phonelinehistory_action"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="phoneline",
            name="telecom_pho_phone_n_72caca_idx",
        ),
        migrations.RemoveIndex(
            model_name="simcard",
            name="telecom_sim_iccid_5f774c_idx",
        ),
    ]
