# Generated by Django 5.2.11 on 2026-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0008_remove_phoneline_telecom_pho_phone_n_72caca_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneline",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponível"),
                    ("ALLOCATED", "Alocado"),
                    ("SUSPENDED", "Quarentena"),
                    ("CANCELLED", "Cancelado"),
                    ("AQUECENDO", "Aquecendo"),
                    ("NOVO", "Novo"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="phonelinehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("STATUS_CHANGED", "Status alterado"),
                    ("SIMCARD_CHANGED", "SIMcard alterado"),
                    ("EMPLOYEE_CHANGED", "Usuário alterado"),
                    ("DELETED", "Excluída"),
                    ("ALLOCATED", "Alocada"),
                    ("RELEASED", "Liberada"),
                    ("DAILY_ACTION_CHANGED", "Ação diária alterada"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
    ]
