# Generated by Django 5.2.11 on 2026-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0009_alter_phoneline_status_alter_phonelinehistory_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneline",
            name="origem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SRVMEMU-01", "SRVMEMU-01"),
                    ("SRVMEMU-02", "SRVMEMU-02"),
                    ("SRVMEMU-03", "SRVMEMU-03"),
                    ("SRVMEMU-04", "SRVMEMU-04"),
                    ("SRVMEMU-05", "SRVMEMU-05"),
                    ("SRVMEMU-06", "SRVMEMU-06"),
                    ("APARELHO", "APARELHO"),
                    ("PESSOAL", "PESSOAL"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
