# Generated by Django 5.2.11 on 2026-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0011_alter_simcard_iccid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlipConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blip_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Blip ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("FLOW", "Fluxo"), ("ROUTER", "Roteador")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descricao"),
                ),
                (
                    "phone_number",
                    models.BigIntegerField(
                        db_index=True, verbose_name="Numero Telefone"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[("ACCESS", "Acesso"), ("HTTP", "Http")],
                        max_length=20,
                        verbose_name="Chave",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Valor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracao Blip",
                "verbose_name_plural": "Configuracoes Blip",
                "ordering": ["blip_id", "phone_number", "type"],
                "indexes": [
                    models.Index(
                        fields=["blip_id", "type"],
                        name="telecom_bli_blip_id_02c634_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "key"],
                        name="telecom_bli_phone_n_5caf0a_idx",
                    ),
                ],
            },
        ),
    ]
