# Generated by Django 5.2.11 on 2026-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0012_blipconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneline',
            name='origem',
            field=models.CharField(blank=True, choices=[('SRVMEMU-01', 'SRVMEMU-01'), ('SRVMEMU-02', 'SRVMEMU-02'), ('SRVMEMU-03', 'SRVMEMU-03'), ('SRVMEMU-04', 'SRVMEMU-04'), ('SRVMEMU-05', 'SRVMEMU-05'), ('SRVMEMU-06', 'SRVMEMU-06'), ('BLIP', 'Blip'), ('APARELHO', 'APARELHO'), ('PESSOAL', 'PESSOAL')], max_length=20, null=True),
        ),
    ]
