# Generated by Django 5.2.11 on 2026-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0014_whatsappreconnecthistory'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='whatsappreconnecthistory',
                    new_name='telecom_wha_phone_l_1edc23_idx',
                    old_name='telecom_wha_phone_l_started_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='phoneline',
            name='canal',
            field=models.CharField(blank=True, choices=[('WEB', 'Whatsapp Web'), ('MYLOOP', 'MyLoop'), ('ANYCALL', 'AnyCall')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneline',
            name='origem',
            field=models.CharField(blank=True, choices=[('SRVMEMU-01', 'SRVMEMU-01'), ('SRVMEMU-02', 'SRVMEMU-02'), ('SRVMEMU-03', 'SRVMEMU-03'), ('SRVMEMU-04', 'SRVMEMU-04'), ('SRVMEMU-05', 'SRVMEMU-05'), ('SRVMEMU-06', 'SRVMEMU-06'), ('BLIP', 'Blip'), ('APARELHO', 'APARELHO'), ('PESSOAL', 'PESSOAL'), ('APARELHO OP', 'Aparelho OP')], max_length=20, null=True),
        ),
    ]
