# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0015_rename_telecom_wha_phone_l_started_idx_telecom_wha_phone_l_1edc23_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonelinehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("STATUS_CHANGED", "Status alterado"),
                    ("SIMCARD_CHANGED", "SIMcard alterado"),
                    ("EMPLOYEE_CHANGED", "Usuário alterado"),
                    ("DELETED", "Excluída"),
                    ("REACTIVATED", "Reativada"),
                    ("ALLOCATED", "Alocada"),
                    ("RELEASED", "Liberada"),
                    ("DAILY_ACTION_CHANGED", "Ação diária alterada"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
    ]
