# Generated by Django 5.2.11 on 2026-02-22 02:39

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemuser',
            managers=[
                ('objects', users.models.SystemUserManager()),
            ],
        ),
    ]
