# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_systemuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super", "Super"),
                    ("gerente", "Gerente"),
                    ("operator", "Operator"),
                ],
                default="operator",
                max_length=20,
            ),
        ),
    ]
