# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_systemuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Gerente vinculado",
            ),
        ),
    ]
