# Generated by Django 5.2.11 on 2026-04-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0006_alter_lineallocation_line_status'),
        ('employees', '0016_rename_employees_e_manager_453265_idx_employees_e_manager_d65f5b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationPendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('no_action', 'Sem Ação'), ('new_number', 'Número Novo'), ('reconnect_whatsapp', 'Reconectar WhatsApp'), ('pending', 'Pendência')], default='no_action', max_length=30, verbose_name='Ação')),
                ('observation', models.CharField(blank=True, default='', max_length=350, verbose_name='Observação')),
                ('last_action_changed_at', models.DateTimeField(blank=True, help_text='Última alteração em Ação ou Status da Linha pelo admin.', null=True, verbose_name='Últ. alt. ação')),
                ('pendency_submitted_at', models.DateTimeField(blank=True, help_text='Quando a ação foi definida como diferente de Sem Ação.', null=True, verbose_name='Envio da pendência')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Quando o admin definiu a ação como Sem Ação.', null=True, verbose_name='Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendency', to='allocations.lineallocation', verbose_name='Alocação')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencies', to='employees.employee', verbose_name='Usuário')),
                ('technical_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pendencies', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pendencies', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Pendência de Alocação',
                'verbose_name_plural': 'Pendências de Alocação',
                'indexes': [models.Index(fields=['employee', 'action'], name='pendencies__employe_4486af_idx'), models.Index(fields=['allocation'], name='pendencies__allocat_781be2_idx')],
            },
        ),
    ]
