# Generated by Django 5.2.11 on 2026-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_rename_departament_employee_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="corporate_email",
            field=models.CharField(max_length=255, verbose_name="Supervisor"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="Carteira"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="teams",
            field=models.CharField(
                choices=[("Joinville", "Joinville"), ("Araquari", "Araquari")],
                max_length=20,
                verbose_name="Unidade",
            ),
        ),
    ]
