# Generated by Django 5.2.11 on 2026-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_corporate_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=50, verbose_name="Carteira"),
        ),
    ]
