# Generated by Django 5.2.11 on 2026-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="corporate_email",
            field=models.CharField(max_length=100, verbose_name="Supervisor"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
    ]
