# Generated by Django 5.2.11 on 2026-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_corporate_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="corporate_email",
            field=models.CharField(max_length=40, verbose_name="Supervisor"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=40),
        ),
    ]
