# Generated by Django 5.2.11 on 2026-02-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_employee_corporate_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=40, verbose_name="Carteira"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="teams",
            field=models.CharField(
                choices=[("Joinville", "Joinville"), ("Araquari", "Araquari")],
                max_length=15,
                verbose_name="Unidade",
            ),
        ),
    ]
