# Generated by Django 5.2.11 on 2026-03-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_alter_employee_employee_id_alter_employee_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Criado"),
                            ("UPDATED", "Atualizado"),
                            ("STATUS_CHANGED", "Status alterado"),
                            ("DELETED", "Desativado"),
                        ],
                        max_length=20,
                        verbose_name="Acao",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor anterior"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="Novo valor"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="employees.employee",
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employeehistory",
            index=models.Index(
                fields=["employee", "-changed_at"], name="employees_employe_0d2ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeehistory",
            index=models.Index(
                fields=["-changed_at"], name="employees_changed_4b53f6_idx"
            ),
        ),
    ]
