# Generated by Django 5.2.11 on 2026-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0009_employeehistory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeehistory",
            new_name="employees_e_employe_98d17e_idx",
            old_name="employees_employe_0d2ee8_idx",
        ),
        migrations.RenameIndex(
            model_name="employeehistory",
            new_name="employees_e_changed_e410c0_idx",
            old_name="employees_changed_4b53f6_idx",
        ),
        migrations.AddField(
            model_name="employee",
            name="pa",
            field=models.CharField(
                blank=True,
                help_text="Preenchimento opcional",
                max_length=100,
                null=True,
                verbose_name="PA",
            ),
        ),
    ]
