# Generated by Django 5.2.11 on 2026-03-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0010_rename_employees_employe_0d2ee8_idx_employees_e_employe_98d17e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "NEGOCIADOR", "verbose_name_plural": "NEGOCIADOR"},
        ),
    ]
