# Generated by Django 5.2.11 on 2026-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_employee_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="line_status",
            field=models.CharField(
                choices=[
                    ("under_analysis", "Em analise"),
                    ("restricted", "Restrito"),
                    ("permanently_banned", "Banido permanentemente"),
                    ("active", "Ativo"),
                ],
                db_index=True,
                default="active",
                help_text="Status da linha do negociador",
                max_length=30,
                verbose_name="Status da linha",
            ),
        ),
    ]
