# Generated by Django 5.2.11 on 2026-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0012_employee_line_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="corporate_email",
            field=models.EmailField(max_length=254, verbose_name="Supervisor"),
        ),
    ]
