# Generated by Django 5.2.11 on 2026-03-10 00:00

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_alter_employee_corporate_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                Lower("full_name"),
                condition=Q(is_deleted=False),
                name="employees_employee_unique_active_full_name_ci",
            ),
        ),
    ]
