# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_employee_unique_active_full_name_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Gerente",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["manager_email"], name="employees_e_manager_453265_idx"),
        ),
    ]
