# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_employee_manager_email"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employee",
            new_name="employees_e_manager_d65f5b_idx",
            old_name="employees_e_manager_453265_idx",
        ),
    ]
