# Generated by Django 5.2.11 on 2026-04-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_rename_employees_e_manager_453265_idx_employees_e_manager_d65f5b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='line_status',
            field=models.CharField(choices=[('under_analysis', 'Em analise'), ('restricted', 'Restrito'), ('permanently_banned', 'Banido permanentemente'), ('waiting_operator', 'Aguardando operador'), ('active', 'Ativo')], db_index=True, default='active', help_text='Status da linha do negociador', max_length=30, verbose_name='Status da linha'),
        ),
    ]
