# Generated by Django 5.2.11 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0018_employee_email_employee_employees_e_email_8f5bbc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="line_status",
            field=models.CharField(
                choices=[
                    ("under_analysis", "Em analise"),
                    ("restricted", "Restrito"),
                    ("web_restriction", "Restrição WEB"),
                    ("permanently_banned", "Banido permanentemente"),
                    ("waiting_operator", "Aguardando operador"),
                    ("active", "Ativo"),
                ],
                db_index=True,
                default="active",
                help_text="Status da linha do negociador",
                max_length=30,
                verbose_name="Status da linha",
            ),
        ),
    ]
