# Generated by Django 5.2.11 on 2026-03-04 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        db_index=True,
                        help_text="Nome do supervisor responsável",
                        max_length=100,
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "portfolio",
                    models.CharField(
                        db_index=True,
                        help_text="Nome da carteira/portfolio",
                        max_length=100,
                        verbose_name="Carteira",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[("B2B", "B2B"), ("B2C", "B2C")],
                        db_index=True,
                        max_length=10,
                        verbose_name="Segmento",
                    ),
                ),
                (
                    "people_logged_in",
                    models.IntegerField(
                        default=0,
                        help_text="Quantidade de pessoas logadas no dia",
                        verbose_name="Pessoas Logadas",
                    ),
                ),
                (
                    "numbers_available",
                    models.IntegerField(
                        default=0,
                        help_text="Números em aquecimento (15+ dias sem alocação)",
                        verbose_name="Números Disponíveis",
                    ),
                ),
                (
                    "numbers_delivered",
                    models.IntegerField(
                        default=0,
                        help_text="Números alocados aos negociadores no dia",
                        verbose_name="Números Entregues",
                    ),
                ),
                (
                    "numbers_reconnected",
                    models.IntegerField(
                        default=0,
                        help_text="Números recuperados e realocados ao mesmo negociador",
                        verbose_name="Números Reconectados",
                    ),
                ),
                (
                    "numbers_new",
                    models.IntegerField(
                        default=0,
                        help_text="Números novos atribuídos no dia",
                        verbose_name="Números Novos",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data do Indicador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_indicators_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_indicators_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador Diário",
                "verbose_name_plural": "Indicadores Diários",
                "ordering": ["-date", "supervisor", "portfolio"],
                "indexes": [
                    models.Index(
                        fields=["date", "segment"], name="dashboard_d_date_7fde36_idx"
                    ),
                    models.Index(
                        fields=["supervisor", "date"],
                        name="dashboard_d_supervi_72b900_idx",
                    ),
                    models.Index(
                        fields=["portfolio", "date"],
                        name="dashboard_d_portfol_7488d0_idx",
                    ),
                    models.Index(
                        fields=["segment", "supervisor", "date"],
                        name="dashboard_d_segment_9242bf_idx",
                    ),
                ],
                "unique_together": {("supervisor", "portfolio", "segment", "date")},
            },
        ),
    ]
