# Generated by Django 5.2.11 on 2026-03-04 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        (
            "employees",
            "0010_rename_employees_employe_0d2ee8_idx_employees_e_employe_98d17e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Dia",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("new_number", "Número novo"),
                            ("reconnect_whatsapp", "Reconectar WhatsApp"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de ação",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_actions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_actions",
                        to="employees.employee",
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_actions_supervised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_actions_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação diária por usuário",
                "verbose_name_plural": "Ações diárias por usuário",
                "ordering": ["-day", "employee__full_name"],
                "indexes": [
                    models.Index(
                        fields=["day", "action_type"], name="dashboard_d_day_d4b9dc_idx"
                    ),
                    models.Index(
                        fields=["employee", "day"],
                        name="dashboard_d_employe_4b5a97_idx",
                    ),
                ],
                "unique_together": {("day", "employee")},
            },
        ),
    ]
