# Generated by Django 5.2.11 on 2026-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_dailyuseraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyuseraction",
            name="is_resolved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marcar quando a ação foi concluída",
                verbose_name="Ação resolvida",
            ),
        ),
    ]
