# Generated by Django 5.2.11 on 2026-03-05 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0004_lineallocation_line_status"),
        ("dashboard", "0003_dailyuseraction_is_resolved"),
        ("employees", "0012_employee_line_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyuseraction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailyuseraction",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_actions",
                to="allocations.lineallocation",
                verbose_name="Alocação da linha",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyuseraction",
            unique_together={("day", "employee", "allocation")},
        ),
        migrations.AddIndex(
            model_name="dailyuseraction",
            index=models.Index(
                fields=["allocation", "day"], name="dashboard_d_allocat_a1bd8e_idx"
            ),
        ),
    ]
