# Generated by Django 5.2.11 on 2026-03-06 16:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allocations",
            "0005_lineallocation_ck_allocation_release_after_allocate_and_more",
        ),
        ("dashboard", "0005_resolve_old_actions"),
        ("employees", "0013_alter_employee_corporate_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyuseraction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dailyindicator",
            name="numbers_available",
            field=models.IntegerField(
                default=0,
                help_text="Números em aquecimento (15+ dias sem alocação)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Números Disponíveis",
            ),
        ),
        migrations.AlterField(
            model_name="dailyindicator",
            name="numbers_delivered",
            field=models.IntegerField(
                default=0,
                help_text="Números alocados aos negociadores no dia",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Números Entregues",
            ),
        ),
        migrations.AlterField(
            model_name="dailyindicator",
            name="numbers_new",
            field=models.IntegerField(
                default=0,
                help_text="Números novos atribuídos no dia",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Números Novos",
            ),
        ),
        migrations.AlterField(
            model_name="dailyindicator",
            name="numbers_reconnected",
            field=models.IntegerField(
                default=0,
                help_text="Números recuperados e realocados ao mesmo negociador",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Números Reconectados",
            ),
        ),
        migrations.AlterField(
            model_name="dailyindicator",
            name="people_logged_in",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade de pessoas logadas no dia",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pessoas Logadas",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyuseraction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allocation__isnull", False)),
                fields=("day", "employee", "allocation"),
                name="uq_daily_action_with_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyuseraction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allocation__isnull", True)),
                fields=("day", "employee", "action_type"),
                name="uq_daily_action_without_allocation",
            ),
        ),
    ]
