# Generated by Django 5.2.11 on 2026-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboarddailysnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboarddailysnapshot',
            new_name='dashboard_d_date_3cb7d7_idx',
            old_name='dashboard_d_date_1cf480_idx',
        ),
    ]
