# Generated by Django 5.2.11 on 2026-03-24 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telecom', '0012_blipconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('health_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='UNKNOWN', max_length=20)),
                ('target_sessions', models.PositiveSmallIntegerField(default=35)),
                ('warning_sessions', models.PositiveSmallIntegerField(default=40)),
                ('max_sessions', models.PositiveSmallIntegerField(default=45)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['health_status', 'is_active'], name='whatsapp_me_health__286b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING_NEW_NUMBER', 'Novo numero'), ('PENDING_RECONNECT', 'Reconectar WhatsApp'), ('CONNECTING', 'Conectando'), ('QR_PENDING', 'QR pendente'), ('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('ERROR', 'Erro')], db_index=True, default='PENDING_NEW_NUMBER', max_length=32)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('qr_last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='telecom.phoneline')),
                ('meow_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_sessions', to='whatsapp.meowinstance')),
            ],
            options={
                'ordering': ['session_id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('HEALTH_CHECK', 'Health check'), ('CREATE_SESSION', 'Create session'), ('GET_SESSION', 'Get session'), ('CONNECT_SESSION', 'Connect session'), ('DELETE_SESSION', 'Delete session'), ('GET_QR', 'Get QR')], max_length=32)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_audits', to='whatsapp.whatsappsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['status', 'is_active'], name='whatsapp_wh_status_415286_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['meow_instance', 'status'], name='whatsapp_wh_meow_in_15a6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappactionaudit',
            index=models.Index(fields=['session', '-created_at'], name='whatsapp_wh_session_6cfa57_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappactionaudit',
            index=models.Index(fields=['action', 'status'], name='whatsapp_wh_action_8e376c_idx'),
        ),
    ]
