# Generated by Django 5.2.11 on 2026-04-06 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_audit_meow_instance(apps, schema_editor):
    audit_model = apps.get_model("whatsapp", "WhatsAppActionAudit")

    for audit in audit_model.objects.filter(
        session__isnull=False,
        meow_instance__isnull=True,
    ).select_related("session"):
        audit.meow_instance_id = audit.session.meow_instance_id
        audit.save(update_fields=["meow_instance"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappscheduledjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappscheduledjob',
            new_name='whatsapp_wh_is_runn_0424b7_idx',
            old_name='whatsapp_wh_is_runn_c9c0af_idx',
        ),
        migrations.AddField(
            model_name='whatsappactionaudit',
            name='meow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_audits', to='whatsapp.meowinstance'),
        ),
        migrations.AlterField(
            model_name='whatsappactionaudit',
            name='action',
            field=models.CharField(choices=[('HEALTH_CHECK', 'Health check'), ('CREATE_SESSION', 'Create session'), ('GET_SESSION', 'Get session'), ('CONNECT_SESSION', 'Connect session'), ('DELETE_SESSION', 'Delete session'), ('GET_QR', 'Get QR'), ('WEBHOOK_EVENT', 'Webhook event')], max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappactionaudit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_audits', to='whatsapp.whatsappsession'),
        ),
        migrations.RunPython(backfill_audit_meow_instance, noop_reverse),
        migrations.AddConstraint(
            model_name='whatsappactionaudit',
            constraint=models.CheckConstraint(condition=models.Q(('session__isnull', False), ('meow_instance__isnull', False), _connector='OR'), name='whatsapp_audit_has_target'),
        ),
    ]
