# Generated by Django 5.2.11 on 2026-04-06 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_rename_whatsapp_wh_is_runn_c9c0af_idx_whatsapp_wh_is_runn_0424b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_code', models.CharField(max_length=64, unique=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_processed_job_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(db_index=True, default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_code'],
            },
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='qr_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WhatsAppIntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CREATE_SESSION', 'Create session'), ('GENERATE_QR', 'Generate QR'), ('SYNC_STATUS', 'Sync status'), ('DELETE_SESSION', 'Delete session')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RETRY', 'Retry'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='PENDING', max_length=16)),
                ('dedupe_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_jobs', to='whatsapp.whatsappsession')),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='whatsapp_wh_status_7f38fe_idx'), models.Index(fields=['session', 'job_type', 'status'], name='whatsapp_wh_session_5accb7_idx')],
            },
        ),
    ]
