# Generated by Django 5.2.11 on 2026-04-06 17:34

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def normalize_whatsapp_session_statuses(apps, schema_editor):
    WhatsAppSession = apps.get_model("whatsapp", "WhatsAppSession")
    status_map = {
        "PENDING_NEW_NUMBER": "NEW",
        "PENDING_RECONNECT": "NEW",
        "CONNECTING": "SESSION_REQUESTED",
        "QR_PENDING": "QR_AVAILABLE",
        "ERROR": "FAILED",
    }
    for old_status, new_status in status_map.items():
        WhatsAppSession.objects.filter(status=old_status).update(status=new_status)


def reverse_whatsapp_session_statuses(apps, schema_editor):
    raise IrreversibleError(
        "A migration 0006 consolida estados legados em menos estados finais da PRD "
        "e nao suporta rollback sem perda de informacao."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappworkerstate_whatsappsession_qr_code_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_whatsapp_session_statuses,
            reverse_whatsapp_session_statuses,
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nova'), ('SESSION_REQUESTED', 'Sessao solicitada'), ('QR_AVAILABLE', 'QR disponivel'), ('WAITING_SCAN', 'Aguardando leitura'), ('CONNECTED', 'Conectado'), ('FAILED', 'Falha'), ('EXPIRED', 'Expirado'), ('DISCONNECTED', 'Desconectado')], db_index=True, default='NEW', max_length=32),
        ),
    ]
