# Generated by Django 5.2.11 on 2026-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_whatsappsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappactionaudit',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappintegrationjob',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
