# Generated by Django 5.2.11 on 2026-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0003_lineallocation_released_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineallocation",
            name="line_status",
            field=models.CharField(
                choices=[
                    ("under_analysis", "Em analise"),
                    ("restricted", "Restrito"),
                    ("permanently_banned", "Banido permanentemente"),
                    ("active", "Ativo"),
                ],
                db_index=True,
                default="active",
                help_text="Status individual da linha",
                max_length=30,
                verbose_name="Status da linha",
            ),
        ),
    ]
