# Generated by Django 5.2.11 on 2026-03-06 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0004_lineallocation_line_status"),
        ("employees", "0013_alter_employee_corporate_email"),
        ("telecom", "0008_remove_phoneline_telecom_pho_phone_n_72caca_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lineallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("released_at__isnull", True),
                    ("released_at__gte", models.F("allocated_at")),
                    _connector="OR",
                ),
                name="ck_allocation_release_after_allocate",
            ),
        ),
        migrations.AddConstraint(
            model_name="lineallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("released_at__isnull", True)),
                    models.Q(("is_active", False), ("released_at__isnull", False)),
                    _connector="OR",
                ),
                name="ck_allocation_active_release_consistency",
            ),
        ),
    ]
