# Generated by Django 5.2.11 on 2026-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allocations",
            "0005_lineallocation_ck_allocation_release_after_allocate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineallocation",
            name="line_status",
            field=models.CharField(
                choices=[
                    ("under_analysis", "Em análise"),
                    ("restricted", "Restrito"),
                    ("permanently_banned", "Banido Permanentemente"),
                    ("active", "Ativo"),
                ],
                db_index=True,
                default="active",
                help_text="Status individual da linha",
                max_length=30,
                verbose_name="Status da linha",
            ),
        ),
    ]
