# Generated by Django 5.2.11 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0007_alter_lineallocation_line_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineallocation",
            name="line_status",
            field=models.CharField(
                choices=[
                    ("under_analysis", "Em análise"),
                    ("restricted", "Restrito"),
                    ("web_restriction", "Restrição WEB"),
                    ("permanently_banned", "Banido Permanentemente"),
                    ("waiting_operator", "Aguardando operador"),
                    ("active", "Ativo"),
                ],
                db_index=True,
                default="active",
                help_text="Status individual da linha",
                max_length=30,
                verbose_name="Status da linha",
            ),
        ),
    ]
